In [1]:
#Import Libraries
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt

In [2]:
sample_string = "This is a pretty good movie"

#Punkt is a tokenizer present in NLTK
nltk.download('punkt')
tokens = nltk.tokenize.word_tokenize(sample_string)
print(tokens)

#We can also manually tokenize
split_words = [words for words in sample_string.split()]
print(split_words)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['This', 'is', 'a', 'pretty', 'good', 'movie']
['This', 'is', 'a', 'pretty', 'good', 'movie']

In [3]:
#A corpus is a large and structured set of machine-readable texts that have been produced in a natural communicative setting.
#Stopwords are words that dont add much meaning to the sentence, that is, if they are removed then the sentence still manages
#pass on most if not all of its meaning
from nltk.corpus import stopwords
nltk.download('stopwords')

#Creating an array of stopwords present in the English language
stopwords = np.array(stopwords.words('english'))
print(stopwords)
print(stopwords.shape)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
['i' 'me' 'my' 'myself' 'we' 'our' 'ours' 'ourselves' 'you' "you're"
 "you've" "you'll" "you'd" 'your' 'yours' 'yourself' 'yourselves' 'he'
 'him' 'his' 'himself' 'she' "she's" 'her' 'hers' 'herself' 'it' "it's"
 'its' 'itself' 'they' 'them' 'their' 'theirs' 'themselves' 'what' 'which'
 'who' 'whom' 'this' 'that' "that'll" 'these' 'those' 'am' 'is' 'are'
 'was' 'were' 'be' 'been' 'being' 'have' 'has' 'had' 'having' 'do' 'does'
 'did' 'doing' 'a' 'an' 'the' 'and' 'but' 'if' 'or' 'because' 'as' 'until'
 'while' 'of' 'at' 'by' 'for' 'with' 'about' 'against' 'between' 'into'
 'through' 'during' 'before' 'after' 'above' 'below' 'to' 'from' 'up'
 'down' 'in' 'out' 'on' 'off' 'over' 'under' 'again' 'further' 'then'
 'once' 'here' 'there' 'when' 'where' 'why' 'how' 'all' 'any' 'both'
 'each' 'few' 'more' 'most' 'other' 'some' 'such' 'no' 'nor' 'not' 'only'
 'own' 'same' 'so' 'than' 'too' 'very' 's' 't' 'can' 'will' 'just' 'don'
 "don't" 'should' "should've" 'now' 'd' 'll' 'm' 'o' 're' 've' 'y' 'ain'
 'aren' "aren't" 'couldn' "couldn't" 'didn' "didn't" 'doesn' "doesn't"
 'hadn' "hadn't" 'hasn' "hasn't" 'haven' "haven't" 'isn' "isn't" 'ma'
 'mightn' "mightn't" 'mustn' "mustn't" 'needn' "needn't" 'shan' "shan't"
 'shouldn' "shouldn't" 'wasn' "wasn't" 'weren' "weren't" 'won' "won't"
 'wouldn' "wouldn't"]
(179,)

In [4]:
#Separating the stopwords from the useful words
useful_words = [x for x in split_words if x not in stopwords]
print(useful_words)

['This', 'pretty', 'good', 'movie']

In [5]:
#Stemming is the process of keeping the root words from a list of similar words
#It may or may not retain any meaning
#For example, 'ban', 'banana', 'bankruptcy', 'banner' all start with 'ban-' but they are not related to each other at all
from nltk.stem import PorterStemmer
ps = PorterStemmer()

test_set = ['ban', 'banana', 'banner', 'bankruptcy']
stemmed = [ps.stem(words) for words in test_set]

#Stemming changes all words to lower case
print(stemmed)

['ban', 'banana', 'banner', 'bankruptci']

In [6]:
#Importing tweet data
data = pd.read_csv('https://raw.githubusercontent.com/dD2405/Twitter_Sentiment_Analysis/master/train.csv')
data.info()
data.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      31962 non-null  int64
 1   label   31962 non-null  int64
 2   tweet   31962 non-null  object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB

    id  label                                              tweet
0    1      0   @user when a father is dysfunctional and is s...
1    2      0  @user @user thanks for #lyft credit i can't us...
2    3      0                                bihday your majesty
3    4      0  #model   i love u take with u all the time in ...
4    5      0             factsguide: society now    #motivation
5    6      0  [2/2] huge fan fare and big talking before the...
6    7      0   @user camping tomorrow @user @user @user @use...
7    8      0  the next school year is the year for exams.ð...
8    9      0  we won!!! love the land!!! #allin #cavs #champ...
9   10      0   @user @user welcome here !  i'm   it's so #gr...
10  11      0   â #ireland consumer price index (mom) climb...
11  12      0  we are so selfish. #orlando #standwithorlando ...
12  13      0  i get to see my daddy today!!   #80days #getti...
13  14      1  @user #cnn calls #michigan middle school 'buil...
14  15      1  no comment!  in #australia   #opkillingbay #se...

In [7]:
import re
def remove_patterns(pattern, text):
  #Finds all matching strings that match the regex pattern provided
  occur = re.findall(pattern, text)
  #Substitutes every such pattern that was found with a empty string
  #and returns the string after every removal
  for match in occur:
    text = re.sub(match, "", text)
  return text

In [8]:
#Adds a new column containing the cleaned data to the original dataframe
data['cleaned'] = [remove_patterns('@[\w]*', sentence) for sentence in data['tweet']]
data.info()
data.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       31962 non-null  int64
 1   label    31962 non-null  int64
 2   tweet    31962 non-null  object
 3   cleaned  31962 non-null  object
dtypes: int64(2), object(2)
memory usage: 998.9+ KB

    id  ...                                            cleaned
0    1  ...    when a father is dysfunctional and is so sel...
1    2  ...    thanks for #lyft credit i can't use cause th...
2    3  ...                                bihday your majesty
3    4  ...  #model   i love u take with u all the time in ...
4    5  ...             factsguide: society now    #motivation
5    6  ...  [2/2] huge fan fare and big talking before the...
6    7  ...                   camping tomorrow        dannyâ¦
7    8  ...  the next school year is the year for exams.ð...
8    9  ...  we won!!! love the land!!! #allin #cavs #champ...
9   10  ...              welcome here !  i'm   it's so #gr8 !
10  11  ...   â #ireland consumer price index (mom) climb...
11  12  ...  we are so selfish. #orlando #standwithorlando ...
12  13  ...  i get to see my daddy today!!   #80days #getti...
13  14  ...   #cnn calls #michigan middle school 'build the...
14  15  ...  no comment!  in #australia   #opkillingbay #se...

[15 rows x 4 columns]

In [9]:
#Further processing, ^ implies 'except' when within regex sets, so it removes everything
#except 'a-z', 'A-Z' and '#' which constitutes hashtags together with the alphabets
data['cleaned'] = data['cleaned'].str.replace("[^a-zA-Z#]", " ")
data.head(15)

    id  ...                                            cleaned
0    1  ...    when a father is dysfunctional and is so sel...
1    2  ...    thanks for #lyft credit i can t use cause th...
2    3  ...                                bihday your majesty
3    4  ...  #model   i love u take with u all the time in ...
4    5  ...             factsguide  society now    #motivation
5    6  ...        huge fan fare and big talking before the...
6    7  ...                   camping tomorrow        danny
7    8  ...  the next school year is the year for exams    ...
8    9  ...  we won    love the land    #allin #cavs #champ...
9   10  ...              welcome here    i m   it s so #gr
10  11  ...       #ireland consumer price index  mom  climb...
11  12  ...  we are so selfish  #orlando #standwithorlando ...
12  13  ...  i get to see my daddy today     #  days #getti...
13  14  ...   #cnn calls #michigan middle school  build the...
14  15  ...  no comment   in #australia   #opkillingbay #se...

[15 rows x 4 columns]

In [10]:
#Here, lambda expressions basically work on every item, x is the item,
#and then the operation is applied on x

#Tokenizing
data['cleaned'] = data['cleaned'].apply(lambda x : x.split())

#Removing stopwords
data['cleaned'] = data['cleaned'].apply(lambda x : [words for words in x if words not in stopwords])

#Stemming
data['cleaned'] = data['cleaned'].apply(lambda x : [ps.stem(words) for words in x])

#Converting each item back to sentence
data['cleaned'] = data['cleaned'].apply(lambda x : ' '.join(x))

#Showing current data
data.head(15)

    id  ...                                            cleaned
0    1  ...     father dysfunct selfish drag kid dysfunct #run
1    2  ...  thank #lyft credit use caus offer wheelchair v...
2    3  ...                                     bihday majesti
3    4  ...                       #model love u take u time ur
4    5  ...                           factsguid societi #motiv
5    6  ...  huge fan fare big talk leav chao pay disput ge...
6    7  ...                                camp tomorrow danni
7    8  ...  next school year year exam think #school #exam...
8    9  ...  love land #allin #cav #champion #cleveland #cl...
9   10  ...                                         welcom #gr
10  11  ...  #ireland consum price index mom climb previou ...
11  12  ...  selfish #orlando #standwithorlando #pulseshoot...
12  13  ...                get see daddi today # day #gettingf
13  14  ...  #cnn call #michigan middl school build wall ch...
14  15  ...  comment #australia #opkillingbay #seashepherd ...

[15 rows x 4 columns]

In [11]:
#Count Vectorizer basically performs a count of every word present as a whole,
#It maps each word to a label and then counts the number of times the labeled words appear
#In each sentence, throughout the document as a whole
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_df=0.8, min_df=2, max_features=1000, stop_words='english')
vectorized_data = vectorizer.fit_transform(data['cleaned'])
vectorized_data = pd.DataFrame(vectorized_data.todense())
vectorized_data.info()
vectorized_data.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Columns: 1000 entries, 0 to 999
dtypes: int64(1000)
memory usage: 243.9 MB

    0    1    2    3    4    5    6    ...  993  994  995  996  997  998  999
0     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
5     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
6     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
7     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
8     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
9     0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
10    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
11    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
12    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
13    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
14    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[15 rows x 1000 columns]

In [12]:
#Test train splitting of data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(vectorized_data, data['label'], test_size = 0.3)

In [13]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
LRClf = LogisticRegression(solver = 'lbfgs').fit(X_train, Y_train)
probab_est = LRClf.predict_proba(X_test)
print(probab_est.shape)
#accuracy_score returns the accuracy by comparing Y_predicted with Y_true
predictions = LRClf.predict(X_test)
accuracy = accuracy_score(predictions, Y_test)
print(accuracy)
#LogisticRegression.score() method does the exact same thing except in one line
print(LRClf.score(X_test, Y_test))

(9589, 2)
0.9478569193867974
0.9478569193867974

In [14]:
#f1_score is used when classes are largely unbalanced, in this case number of happy tweets
#largely outnumbers the number of sad tweets
from sklearn.metrics import f1_score
print(np.unique(predictions, return_counts=True))
f1_accuracy = f1_score(predictions, Y_test)
print(f1_accuracy)

(array([0, 1]), array([9262,  327]))
0.50199203187251

In [15]:
#SVM
from sklearn import svm
SVMClf = svm.SVC().fit(X_train, Y_train)
predictions = SVMClf.predict(X_test)
accuracy = accuracy_score(predictions, Y_test)
print(accuracy)
#f1 score from SVM
f1_accuracy = f1_score(predictions, Y_test)
print(f1_accuracy)

0.9504640734174575
0.5046923879040668

In [16]:
#TfidfVectorizer provides the same results as CountVectorizer followed by TfidfTranformer
#Tf stands for Term-frequency
#Idf stands for Inverse document frequency
#The picture at https://miro.medium.com/max/1050/1*qQgnyPLDIkUmeZKN2_ZWbQ.png explains the concept in a nutshell
#In TfidfVectorizer we consider overall document weightage of a word. It helps us in dealing with most frequent words.
#Using it we can penalize them. TfidfVectorizer weights the word counts by a measure of how often they appear in the documents.
#If a word appears in every document, it is not so unique hence its actual affect on the meaning must be low, but not zero

#Using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvectorizer = TfidfVectorizer(max_df=0.8, min_df=2, max_features=1000, stop_words='english')
tfidfvectorized_data = tfidfvectorizer.fit_transform(data['cleaned'])
tfidfvectorized_data = pd.DataFrame(tfidfvectorized_data.todense())
X_train, X_test, Y_train, Y_test = train_test_split(tfidfvectorized_data, data['label'], test_size = 0.3)

#SVM using default kernel
TfidfSVMClf = svm.SVC().fit(X_train, Y_train)
predictions = TfidfSVMClf.predict(X_test)
accuracy = accuracy_score(predictions, Y_test)
print(accuracy)
#f1 score from SVM
f1_accuracy = f1_score(predictions, Y_test)
print(f1_accuracy)

#SVM with linear kernel
LinKernSVMClf = svm.SVC(kernel='linear').fit(X_train, Y_train)
predictions = LinKernSVMClf.predict(X_test)
accuracy = accuracy_score(predictions, Y_test)
print(accuracy)
#f1 score from SVM
f1_accuracy = f1_score(predictions, Y_test)
print(f1_accuracy)

0.9557826676400042
0.5583333333333333
0.95213265199708
0.5311542390194075